import Head from "next/head";
import Footer from "./footer";
import Header from "./menu";
import { useQuery } from "react-query";
import { request, gql } from "graphql-request";

const Layout = ({ children }) => {
  const endpoint = process.env.ENDPOINT;
  const getFM = (endpoint) => {
    const { data } = useQuery("menuItems", async () => {
      const menus = await request(
        endpoint,
        gql`
          query {
            header: menuItems(where: { location: PRIMARY }) {
              nodes {
                id
                label
                path
                url
              }
            }
            footer: menuItems(where: { location: FOOTER }) {
              nodes {
                id
                label
                path
                url
              }
            }
          }
        `
      );
      return menus;
    });

    return data || [];
  };
  const { header, footer } = getFM(endpoint);
  return (
    <div>
      <Head>
        <title>Wak | Just Another WordPress Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header headerMenu={header?.nodes} />
      {children}
      <Footer footerMenu={footer?.nodes} />
    </div>
  );
};

export default Layout;
